package preflight

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WSL2's GPU passthrough is a library path, not a kernel driver.
//
// Measured on a working WSL2 host with an RTX 5090:
//
//	/proc/driver/nvidia/          absent — no in-distribution kernel module
//	/dev/                         dxg and nvidiactl; no /dev/nvidia0
//	/etc/ld.so.conf.d/ld.wsl.conf generated by WSL, holding /usr/lib/wsl/lib
//	ldconfig -p | libcuda.so.1    /usr/lib/wsl/lib/libcuda.so.1   <- first
//	                              /lib/x86_64-linux-gnu/libcuda.so.1
//
// The last two lines are the whole check. A distribution-installed NVIDIA
// userland is *already here* and passthrough works anyway, because WSL's
// directory comes first in the loader cache. What breaks a host is that
// ordering inverting — which is what installing an in-distribution display
// driver does — and the symptom is every CUDA container failing at start with
// an error about the driver, on a machine whose `nvidia-smi` still answers.
const (
	wslLibDir    = "/usr/lib/wsl/lib"
	wslCUDA      = "libcuda.so.1"
	nvidiaKmod   = "/proc/driver/nvidia/version"
	nvidiaAdvice = "NVIDIA's own guidance is that no Linux display driver is installed inside a\n" +
		"    WSL2 distribution: the Windows driver provides the device through /dev/dxg."
)

// checkWSLPassthrough is R5-03's second half: CUDA passthrough broken by an
// in-distribution driver fails here rather than at the first deployment.
//
// A node-role hard failure, because a node whose containers cannot reach the
// GPU is a node that will accept work and fail all of it.
func checkWSLPassthrough(ctx context.Context, o Options, h hostFS) Check {
	c := Check{Name: "wsl gpu", Level: LevelSkip}
	if !isWSLIn(h) {
		c.Detail = "not a WSL2 host"
		return c
	}

	// The kernel module is the unambiguous one: WSL2 binds the GPU through
	// dxgkrnl, so this file exists only if somebody installed a driver that
	// cannot work here.
	if _, err := os.Stat(h.path(nvidiaKmod)); err == nil {
		c.Level = LevelFail
		c.Detail = "an in-distribution NVIDIA kernel driver is loaded (" + nvidiaKmod + " exists),\n" +
			"    which breaks the /dev/dxg passthrough this host serves GPUs through.\n    " +
			nvidiaAdvice
		return c
	}

	if _, err := os.Stat(h.path(filepath.Join(wslLibDir, wslCUDA))); err != nil {
		c.Level = LevelFail
		c.Detail = wslLibDir + "/" + wslCUDA + " is missing, so nothing in a container can open\n" +
			"    the GPU. Install the NVIDIA driver on Windows, not in this distribution, and\n" +
			"    restart it with `wsl --shutdown`."
		return c
	}

	// Which copy wins. A check for the WSL library's mere presence would pass
	// on exactly the broken host this exists to catch, because installing a
	// distribution driver does not remove it — it gets in front of it.
	out, err := o.exec(ctx, "ldconfig", "-p")
	if err != nil {
		// A check that cannot run is not a check that passed (R5-01).
		c.Level, c.Detail = LevelSkip, "ldconfig is not usable, so the loader order is unknown: "+err.Error()
		return c
	}
	winner, found := firstLoaderPath(string(out), wslCUDA)
	switch {
	case !found:
		c.Level = LevelWarn
		c.Detail = wslCUDA + " is not in the loader cache; run `sudo ldconfig` and re-check"
	case !strings.HasPrefix(winner, wslLibDir):
		c.Level = LevelFail
		c.Detail = fmt.Sprintf("%s resolves to %s before %s/%s, so a container gets the\n"+
			"    distribution's driver library instead of the passthrough one and CUDA fails at\n"+
			"    start.\n    %s", wslCUDA, winner, wslLibDir, wslCUDA, nvidiaAdvice)
	default:
		c.Level, c.Detail = LevelOK, winner
	}
	return c
}

// firstLoaderPath reads `ldconfig -p` and returns the path the loader would
// pick for a soname: the first entry, since the cache is searched in order.
func firstLoaderPath(listing, soname string) (string, bool) {
	for _, line := range strings.Split(listing, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, soname+" ") {
			continue
		}
		_, path, ok := strings.Cut(line, " => ")
		if !ok {
			continue
		}
		return strings.TrimSpace(path), true
	}
	return "", false
}
