package preflight

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WSL2's GPU passthrough is a library path, not a kernel driver.
//
// Measured on a working WSL2 host with an RTX 5090:
//
//	/proc/driver/nvidia/          absent — no in-distribution kernel module
//	/dev/                         dxg and nvidiactl; no /dev/nvidia0
//	/etc/ld.so.conf.d/ld.wsl.conf generated by WSL, holding /usr/lib/wsl/lib
//	ldconfig -p | libcuda.so.1    /usr/lib/wsl/lib/libcuda.so.1   <- first
//	                              /lib/x86_64-linux-gnu/libcuda.so.1
//
// The last two lines are the whole check. A distribution-installed NVIDIA
// userland is *already here* and passthrough works anyway, because WSL's
// directory comes first in the loader cache. What breaks a host is that
// ordering inverting — which is what installing an in-distribution display
// driver does — and the symptom is every CUDA container failing at start with
// an error about the driver, on a machine whose `nvidia-smi` still answers.
const (
	wslLibDir    = "/usr/lib/wsl/lib"
	wslCUDA      = "libcuda.so.1"
	nvidiaKmod   = "/proc/driver/nvidia/version"
	nvidiaAdvice = "NVIDIA's own guidance is that no Linux display driver is installed inside a\n" +
		"    WSL2 distribution: the Windows driver provides the device through /dev/dxg."
)

// checkWSLPassthrough is R5-03's second half: CUDA passthrough broken by an
// in-distribution driver fails here rather than at the first deployment.
//
// A node-role hard failure, because a node whose containers cannot reach the
// GPU is a node that will accept work and fail all of it.
func checkWSLPassthrough(ctx context.Context, o Options, h hostFS) Check {
	c := Check{Name: "wsl gpu", Level: LevelSkip}
	if !isWSLIn(h) {
		c.Detail = "not a WSL2 host"
		return c
	}

	// The kernel module is the unambiguous one: WSL2 binds the GPU through
	// dxgkrnl, so this file exists only if somebody installed a driver that
	// cannot work here.
	if _, err := os.Stat(h.path(nvidiaKmod)); err == nil {
		c.Level = LevelFail
		c.Detail = "an in-distribution NVIDIA kernel driver is loaded (" + nvidiaKmod + " exists),\n" +
			"    which breaks the /dev/dxg passthrough this host serves GPUs through.\n    " +
			nvidiaAdvice
		return c
	}

	if _, err := os.Stat(h.path(filepath.Join(wslLibDir, wslCUDA))); err != nil {
		c.Level = LevelFail
		c.Detail = wslLibDir + "/" + wslCUDA + " is missing, so nothing in a container can open\n" +
			"    the GPU. Install the NVIDIA driver on Windows, not in this distribution, and\n" +
			"    restart it with `wsl --shutdown`."
		return c
	}

	// Which copy wins. A check for the WSL library's mere presence would pass
	// on exactly the broken host this exists to catch, because installing a
	// distribution driver does not remove it — it gets in front of it.
	out, err := o.exec(ctx, "ldconfig", "-p")
	if err != nil {
		// A check that cannot run is not a check that passed (R5-01).
		c.Level, c.Detail = LevelSkip, "ldconfig is not usable, so the loader order is unknown: "+err.Error()
		return c
	}
	winner, found := firstLoaderPath(string(out), wslCUDA)
	switch {
	case !found:
		c.Level = LevelWarn
		c.Detail = wslCUDA + " is not in the loader cache; run `sudo ldconfig` and re-check"
	case !strings.HasPrefix(winner, wslLibDir):
		c.Level = LevelFail
		c.Detail = fmt.Sprintf("%s resolves to %s before %s/%s, so a container gets the\n"+
			"    distribution's driver library instead of the passthrough one and CUDA fails at\n"+
			"    start.\n    %s", wslCUDA, winner, wslLibDir, wslCUDA, nvidiaAdvice)
	default:
		c.Level, c.Detail = LevelOK, winner
	}
	return c
}

// firstLoaderPath reads `ldconfig -p` and returns the path the loader would
// pick for a soname: the first entry, since the cache is searched in order.
func firstLoaderPath(listing, soname string) (string, bool) {
	for _, line := range strings.Split(listing, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, soname+" ") {
			continue
		}
		_, path, ok := strings.Cut(line, " => ")
		if !ok {
			continue
		}
		return strings.TrimSpace(path), true
	}
	return "", false
}

// The two performance traps dev/specs/01-install.md §8 names, as warnings.
//
// Both are slow rather than broken, which is exactly why they are worth saying
// at install: a node that works and is inexplicably slow costs more of an
// operator's time than one that refuses.

// checkWSLModelsDir catches weights on the Windows filesystem.
//
// Anything under /mnt is 9p, where staging a model is pathologically slow —
// and the symptom is a download that crawls on a machine whose network is
// fine, which reads as a problem with the mirror.
func checkWSLModelsDir(o Options, h hostFS) Check {
	c := Check{Name: "wsl models dir", Level: LevelSkip}
	if !isWSLIn(h) {
		c.Detail = "not a WSL2 host"
		return c
	}
	if o.ModelsDir == "" {
		c.Detail = "no models directory to check"
		return c
	}
	if !strings.HasPrefix(filepath.Clean(o.ModelsDir)+string(filepath.Separator), "/mnt/") {
		c.Level, c.Detail = LevelOK, o.ModelsDir+" is on the distribution's own filesystem"
		return c
	}
	c.Level = LevelWarn
	c.Detail = o.ModelsDir + " is on the Windows filesystem, reached over 9p, where staging\n" +
		"    a model is pathologically slow. Put it on the distribution's own disk."
	return c
}

// wslConfigGlob is where Windows keeps the file that sizes the WSL2 VM. A glob
// rather than the invoking user's profile, because reading %USERPROFILE% costs
// a second of Windows interop to answer a question a directory listing answers.
const wslConfigGlob = "/mnt/c/Users/*/.wslconfig"

// checkWSLMemory catches a VM sized at half the host.
//
// WSL2 caps the virtual machine near 50% of the host's RAM unless `.wslconfig`
// says otherwise, which on a 64GB workstation is 32GB — enough to look fine
// and not enough for the model somebody sized against the machine they bought.
func checkWSLMemory(h hostFS) Check {
	c := Check{Name: "wsl memory", Level: LevelSkip}
	if !isWSLIn(h) {
		c.Detail = "not a WSL2 host"
		return c
	}
	found, _ := filepath.Glob(h.path(wslConfigGlob))
	for _, path := range found {
		body, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(body), "\n") {
			// `memory=` and not `memory =`: both are accepted by WSL, so the
			// space is stripped before the compare rather than being a second
			// pattern that can be forgotten.
			if strings.HasPrefix(strings.ReplaceAll(strings.TrimSpace(line), " ", ""), "memory=") {
				c.Level = LevelOK
				c.Detail = ".wslconfig sizes this VM explicitly"
				return c
			}
		}
	}
	c.Level = LevelWarn
	c.Detail = "no .wslconfig sets `memory=`, so WSL2 caps this VM near half the host's RAM.\n" +
		"    A model sized against the machine's specification will not fit."
	return c
}
