package agent

import (
	"crypto/sha256"
	"encoding/hex"
	"net/netip"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// stagingDownloader is the agent half: a Downloader that starts units and
// never fetches anything itself, wired to a systemd that records what it was
// asked to do.
func stagingDownloader(t *testing.T) (*Downloader, *fakeHost) {
	t.Helper()
	h, f := newFakeHost(t)
	h.Self = "/usr/local/bin/nodary"
	return &Downloader{BaseURL: "https://huggingface.co", Host: h}, f
}

// property returns the value of one --property=NAME= argument out of a
// systemd-run command line. Split on the flag rather than on whitespace: an
// address list is one argument containing spaces, which is the whole reason
// the filter is two properties instead of a dozen.
func property(call, name string) string {
	for _, f := range strings.Split(call, "--property=") {
		if v, ok := strings.CutPrefix(f, name+"="); ok {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

func firstCall(t *testing.T, f *fakeHost, prefix string) string {
	t.Helper()
	f.mu.Lock()
	defer f.mu.Unlock()
	for _, c := range f.calls {
		if strings.HasPrefix(c, prefix) {
			return c
		}
	}
	t.Fatalf("no %q command was run. calls: %v", prefix, f.calls)
	return ""
}

// R4-30: the filter's whole job is the enclave. Each of these ranges is a
// place the control plane, a peer node, the customer's own network or the
// cloud metadata service lives, and a weight download reaching any of them is
// the lateral movement moving staging out of the agent process was for.
func TestTheStagingFilterDeniesTheEnclave(t *testing.T) {
	deny := property(strings.Join(stageFilter("/nonexistent"), " "), "IPAddressDeny")
	for _, want := range []string{
		"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "100.64.0.0/10",
		"169.254.0.0/16", "127.0.0.0/8", "fc00::/7", "fe80::/10",
	} {
		if !strings.Contains(deny, want) {
			t.Errorf("IPAddressDeny does not carry %s.\n  got: %s", want, deny)
		}
	}
	// The metadata endpoint by name, because it is the one whose absence
	// would be a credential handout rather than a reachability nuisance.
	if !netip.MustParsePrefix("169.254.0.0/16").Contains(netip.MustParseAddr("169.254.169.254")) {
		t.Fatal("169.254.169.254 is not covered by the range this filter denies")
	}
}

// The filter is correct only because systemd resolves overlapping rules by
// longest matching prefix. A resolver on the LAN sits inside a range the
// filter denies, and the only thing that lets it through is its own entry
// being more specific. If that ever stopped holding, the filter would look
// exactly as it does now and block DNS on every host with a site resolver.
func TestTheFilterDependsOnLongestPrefixWinning(t *testing.T) {
	conf := filepath.Join(t.TempDir(), "resolv.conf")
	os.WriteFile(conf, []byte("nameserver 192.168.1.53\n"), 0o644)

	props := strings.Join(stageFilter(conf), " ")
	allow := property(props, "IPAddressAllow")
	if !strings.Contains(allow, "192.168.1.53") {
		t.Fatalf("IPAddressAllow = %q, want it to carry the resolver", allow)
	}

	// Read out of the filter rather than assumed, so widening the entry is
	// caught here and not only by whoever loses DNS in production.
	var one netip.Prefix
	for _, a := range strings.Fields(allow) {
		p, err := netip.ParsePrefix(a)
		if err == nil && p.Contains(netip.MustParseAddr("192.168.1.53")) {
			one = p
		}
	}
	if !one.IsValid() {
		t.Fatalf("IPAddressAllow = %q carries no prefix covering the resolver", allow)
	}
	for _, d := range strings.Fields(property(props, "IPAddressDeny")) {
		p, err := netip.ParsePrefix(d)
		if err != nil || !p.Contains(netip.MustParseAddr("192.168.1.53")) {
			continue
		}
		if p.Bits() >= one.Bits() {
			t.Errorf("deny %s is at least as specific as the allow %s, so the resolver "+
				"does not win and name resolution fails inside the staging unit", d, one)
		}
	}
}

func TestTheStagingFilterAllowsThisHostsResolvers(t *testing.T) {
	conf := filepath.Join(t.TempDir(), "resolv.conf")
	os.WriteFile(conf, []byte(
		"# generated by something\n"+
			"search corp.example\n"+
			"nameserver 192.168.1.53\n"+
			"nameserver fe80::1%eth0\n"+
			"nameserver 192.168.1.53\n"+
			"nameserver not-an-address\n"), 0o644)

	allow := property(strings.Join(stageFilter(conf), " "), "IPAddressAllow")
	fields := strings.Fields(allow)
	if len(fields) == 0 || fields[0] != "any" {
		t.Fatalf("IPAddressAllow = %q, want it to start with any", allow)
	}
	// The zone is gone: systemd wants the address, and fe80::1%eth0 is not one.
	want := []string{"any", "192.168.1.53/32", "fe80::1/128"}
	if strings.Join(fields, " ") != strings.Join(want, " ") {
		t.Errorf("IPAddressAllow = %v, want %v — deduplicated, zone stripped, "+
			"and a line that is not an address skipped rather than passed through", fields, want)
	}
}

// An unreadable resolv.conf must not silently produce a filter that blocks
// DNS: staging would then fail on every host with a name that cannot be
// resolved, which reads as a network outage rather than as a filter.
func TestAnUnreadableResolvConfStillLeavesAResolver(t *testing.T) {
	allow := property(strings.Join(stageFilter("/nonexistent"), " "), "IPAddressAllow")
	if !strings.Contains(allow, "127.0.0.53/32") {
		t.Errorf("IPAddressAllow = %q, want the systemd-resolved stub as a fallback", allow)
	}
	// And not loopback wholesale: a single-box install's own control plane
	// listens there.
	if strings.Contains(allow, "127.0.0.0/8") {
		t.Error("the fallback opened all of loopback, which reaches the control plane " +
			"on a single-box install")
	}
}

// R4-30's core: a download is a transient unit, not a goroutine in the root
// daemon holding this node's mTLS key.
func TestStagingRunsInAUnitOfItsOwn(t *testing.T) {
	dl, f := stagingDownloader(t)
	dl.Token = "hf_secret"
	dir := filepath.Join(t.TempDir(), "models--acme--tiny")

	if st := dl.Status("acme/tiny", "manifest body", "abc", dir); st.State != StateStaging {
		t.Fatalf("state = %s (%s), want staging", st.State, st.Reason)
	}

	call := firstCall(t, f, "systemd-run")
	for _, want := range []string{
		"--unit=" + stageUnitName("acme/tiny"),
		"--collect",
		"--property=IPAddressDeny=",
		"--property=IPAddressAllow=",
		"/usr/local/bin/nodary agent stage --request " + requestPath(dir),
	} {
		if !strings.Contains(call, want) {
			t.Errorf("the staging unit's command line is missing %q.\n  got: %s", want, call)
		}
	}

	// The token reaches the child through a file only. On a command line it
	// is in `ps` for every local user while systemd-run runs, and in
	// `systemctl show` for the life of the unit.
	if strings.Contains(call, "hf_secret") {
		t.Error("HF_TOKEN is on the staging unit's command line, where every local user can read it")
	}
	req, err := readStageRequest(requestPath(dir))
	if err != nil {
		t.Fatal(err)
	}
	if req.Token != "hf_secret" || req.ManifestBody != "manifest body" || req.ManifestSHA256 != "abc" {
		t.Errorf("request = %+v, want the token, the manifest and its digest carried to the child", req)
	}
	fi, err := os.Stat(requestPath(dir))
	if err != nil {
		t.Fatal(err)
	}
	if fi.Mode().Perm() != 0o600 {
		t.Errorf("the staging request is mode %o, want 600: it holds HF_TOKEN", fi.Mode().Perm())
	}
}

// Status runs every reconcile cycle, about once a minute, for as long as a
// multi-hour download lasts. Starting a second unit each time is the failure
// this replaces the in-memory map's job of preventing.
func TestStatusDoesNotStartASecondUnitWhileOneIsRunning(t *testing.T) {
	dl, f := stagingDownloader(t)
	dir := filepath.Join(t.TempDir(), "models--acme--tiny")

	dl.Status("acme/tiny", "manifest", "abc", dir)
	dl.Status("acme/tiny", "manifest", "abc", dir)
	dl.Status("acme/tiny", "manifest", "abc", dir)

	if n := f.count("systemd-run"); n != 1 {
		t.Errorf("%d staging units started for one model, want 1", n)
	}
}

// The verdict is a file now, so it outlives the unit that wrote it *and* the
// agent process. The in-memory map it replaces forgot `corrupt` on every
// agent restart, which is most of the way to the silent re-download R4-35
// exists to prevent.
func TestATerminalVerdictOutlivesTheUnit(t *testing.T) {
	for _, state := range []string{StateStaged, StateCorrupt} {
		t.Run(state, func(t *testing.T) {
			dl, f := stagingDownloader(t)
			dir := filepath.Join(t.TempDir(), "models--acme--tiny")
			os.MkdirAll(filepath.Dir(dir), 0o755)
			(&progress{path: progressPath(dir)}).set(state, 10, 10, "settled")

			st := dl.Status("acme/tiny", "manifest", "abc", dir)
			if st.State != state {
				t.Errorf("state = %s, want the recorded %s", st.State, state)
			}
			if f.did("systemd-run") {
				t.Errorf("a unit was started for a model already recorded %s", state)
			}
		})
	}
}

// A reboot, an OOM kill or an agent replaced mid-transfer leaves progress that
// is not terminal and no unit running. That has to start again rather than sit
// at a percentage forever — and it is safe, because every file that already
// verifies on disk is skipped.
func TestAnInterruptedDownloadIsStartedAgain(t *testing.T) {
	dl, f := stagingDownloader(t)
	dir := filepath.Join(t.TempDir(), "models--acme--tiny")
	os.MkdirAll(filepath.Dir(dir), 0o755)
	(&progress{path: progressPath(dir)}).set(StateStaging, 400, 1000, "")

	if st := dl.Status("acme/tiny", "manifest", "abc", dir); st.State != StateStaging {
		t.Fatalf("state = %s, want staging", st.State)
	}
	if !f.did("systemd-run") {
		t.Error("a download interrupted partway was never started again")
	}
}

// Reset has to stop the unit before it deletes anything: one still writing
// into <dir>.downloading would recreate part of what is being removed, and the
// leftovers would be attributed to the next attempt.
func TestResetStopsTheUnitBeforeItDeletes(t *testing.T) {
	dl, f := stagingDownloader(t)
	dir := filepath.Join(t.TempDir(), "models--acme--tiny")
	os.MkdirAll(dir, 0o755)
	(&progress{path: progressPath(dir)}).set(StateCorrupt, 0, 0, "bad")

	if !dl.Reset("acme/tiny", dir) {
		t.Fatal("Reset reported failure")
	}
	if !f.did("systemctl stop " + stageUnitName("acme/tiny")) {
		t.Error("Reset did not stop the staging unit")
	}
	if _, ok := readProgress(progressPath(dir)); ok {
		t.Error("Reset left the old verdict behind, so the next Status would replay it forever")
	}
}

// A model id is an arbitrary string and a unit name is not, so the readable
// part is sanitized — which maps these two onto the same name. Two models
// downloading into each other's unit presents as weights that are
// inexplicably the wrong ones.
func TestModelsThatSanitizeAlikeGetDifferentUnits(t *testing.T) {
	if a, b := stageUnitName("acme/tiny"), stageUnitName("acme-tiny"); a == b {
		t.Errorf("both models use the unit %s", a)
	}
	for _, model := range []string{"acme/tiny", strings.Repeat("x", 200), "a b/c:d"} {
		name := stageUnitName(model)
		if !strings.HasSuffix(name, ".service") || len(name) > 255 {
			t.Errorf("stageUnitName(%q) = %q, which systemd will not accept", model, name)
		}
		for _, r := range strings.TrimSuffix(name, ".service") {
			switch {
			case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9',
				r == '-', r == '_', r == '.':
			default:
				t.Errorf("stageUnitName(%q) = %q contains %q", model, name, r)
			}
		}
	}
}

// A site that reaches the internet through a proxy has to keep working. It did
// before R4-30 by accident — the download ran inside the agent process, which
// inherits the drop-in an operator puts HF_TOKEN in — and moving it into a
// transient unit broke that twice over: a clean environment carries no
// setting, and the filter denies the private range a proxy sits in.
func TestAProxyOnTheLANIsCarriedAndLetThrough(t *testing.T) {
	conf := filepath.Join(t.TempDir(), "resolv.conf")
	os.WriteFile(conf, []byte("nameserver 127.0.0.53\n"), 0o644)

	allow := property(strings.Join(stageFilter(conf, proxyPrefixes("http://10.20.0.5:3128")...), " "),
		"IPAddressAllow")
	if !strings.Contains(allow, "10.20.0.5/32") {
		t.Fatalf("IPAddressAllow = %q, want the proxy through", allow)
	}
	// And more specific than the deny covering it, or it does not win.
	one := netip.MustParsePrefix("10.20.0.5/32")
	for _, d := range strings.Fields(property(strings.Join(stageFilter(conf), " "), "IPAddressDeny")) {
		if p, err := netip.ParsePrefix(d); err == nil && p.Contains(one.Addr()) && p.Bits() >= one.Bits() {
			t.Errorf("deny %s is at least as specific as the proxy's %s", d, one)
		}
	}

	// A bare host:port is legal in these variables and is not a URL:
	// url.Parse reads "10.20.0.5:3128" as the scheme "10.20.0.5".
	if got := proxyPrefixes("10.20.0.5:3128"); len(got) != 1 || got[0] != "10.20.0.5/32" {
		t.Errorf("proxyPrefixes on a bare host:port = %v, want [10.20.0.5/32]", got)
	}
	// A name that does not resolve contributes nothing rather than failing:
	// the filter is then no wider than before and the operator sees a
	// connection refused they can act on.
	if got := proxyPrefixes("http://proxy.invalid:3128"); len(got) != 0 {
		t.Errorf("proxyPrefixes on an unresolvable name = %v, want none", got)
	}

	dl, f := stagingDownloader(t)
	dl.Proxy = "http://10.20.0.5:3128"
	dir := filepath.Join(t.TempDir(), "models--acme--tiny")
	dl.Status("acme/tiny", "manifest", "abc", dir)

	call := firstCall(t, f, "systemd-run")
	if !strings.Contains(property(call, "IPAddressAllow"), "10.20.0.5/32") {
		t.Errorf("the staging unit cannot reach the proxy it is supposed to use.\n  got: %s", call)
	}
	req, err := readStageRequest(requestPath(dir))
	if err != nil {
		t.Fatal(err)
	}
	if req.Proxy != "http://10.20.0.5:3128" {
		t.Errorf("request proxy = %q, want it carried: the unit inherits no environment", req.Proxy)
	}
	// A proxy URL may carry credentials, so it travels the same way the token
	// does and not on a command line every local user can read.
	if strings.Contains(call, "10.20.0.5:3128") && strings.Contains(call, "--setenv") {
		t.Error("the proxy setting is on the staging unit's command line")
	}
}

// End to end through a proxy: the child is pointed at a base URL that does not
// resolve, and reaches the fixture anyway because every request goes to the
// proxy as an absolute URI.
func TestTheChildDownloadsThroughItsProxy(t *testing.T) {
	srv, manifest := remoteFixture(t, map[string]string{"config.json": `{"model_type":"tiny"}`})
	defer srv.Close()
	digest := sha256.Sum256([]byte(manifest))

	dir := filepath.Join(t.TempDir(), "models--acme--tiny")
	if err := writeStageRequest(requestPath(dir), stageRequest{Model: "acme/tiny", Dir: dir,
		BaseURL: "http://huggingface.invalid", ManifestBody: manifest,
		ManifestSHA256: hex.EncodeToString(digest[:]), Proxy: srv.URL}); err != nil {
		t.Fatal(err)
	}
	st, err := RunStaging(requestPath(dir))
	if err != nil {
		t.Fatal(err)
	}
	if st.State != StateStaged {
		t.Fatalf("state = %s (%s), want staged: the download did not go through the proxy",
			st.State, st.Reason)
	}
}
