-- When a node's client certificate stops being accepted
-- (docs/specs/02-enrollment.md 3).
--
-- It is here rather than derived from the certificate on disk because the
-- control plane never holds that file: it signs the certificate, hands it over
-- and keeps only what it needs to reason about the fleet. Two decisions rest
-- on this column.
--
-- Renewal at two-thirds of lifetime is the agent's, and the agent has its own
-- copy. Re-enrollment is the server's: docs/plans/R4a-agent-protocol.md 8
-- allows a node to enroll under a name that already exists only once the
-- recorded certificate has expired, so that a leaked join token plus a guessed
-- name cannot replace a live node's identity -- and inherit its approval.
--
-- Nullable, because every node enrolled before this migration has a
-- certificate whose expiry nobody recorded. NULL reads as "unknown", and
-- unknown refuses re-enrollment rather than permitting it.
ALTER TABLE node ADD COLUMN cert_expires_at TEXT;
