package config

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/nodarynet/nodary/internal/audit"
	"github.com/nodarynet/nodary/internal/backend"
	"github.com/nodarynet/nodary/internal/policy"
)

// ErrUnknownNode is returned when a configuration names a node that has never
// enrolled.
var ErrUnknownNode = errors.New("unknown node")

// ErrInvalid is a document this control plane will not apply because of what is
// in it, rather than because of who asked.
//
// It exists so both front ends answer the same way: without it, a deployment
// naming a model that does not exist — an operator's typo in a file — was an
// unrecognized error, which internal/api renders as 500 with the message
// deliberately withheld. A malformed document is the caller's to fix and they
// have to be told what is wrong with it.
var ErrInvalid = errors.New("invalid configuration")

// Result says what an apply did, so a caller can report it and a --dry-run can
// report it without doing it.
type Result struct {
	Changes []string
	// Orphans are objects in the database and absent from the configuration.
	// They are left alone unless Prune is set — see Options.
	Orphans []string
}

// Options controls an apply.
type Options struct {
	// Prune deletes objects the configuration does not mention.
	//
	// Off by default, and that default is the whole decision: the alternative
	// makes `config apply -f partial.toml` a fleet-wide delete, and the first
	// person to run it against a hand-written fragment loses their deployments.
	// Reconcile-to-absent assumes the file was generated by the same system,
	// which `config export` produces and a human writing a fragment does not.
	Prune bool
}

// Apply writes a snapshot into the database.
//
// One applier, three entrances: `config apply -f`, `config rollback`, and the
// tests. If rollback had its own it would be the one that drifts, and the drift
// would surface as "the rollback did not restore what export said was there" —
// discovered during a recovery, which is the worst possible time.
// FilterChanges drops `- ` lines from a change list when prune is off.
//
// **A `-` line is a deletion, and with prune off no deletion happens.** Those
// objects are Orphans, reported separately as left in place. Leaving them in
// the list makes an ordinary partial apply say it removed the node the
// operator is standing on — which is the most alarming thing this verb could
// say untruthfully.
//
// Exported and called from two places that both render a change list and must
// agree: Apply's own Result, and the CLI's preview shown before "apply? [y/N]"
// and hashed into intent_hash. The preview used to call Changes directly,
// unfiltered — so the confirmation an operator actually approves said this on
// every partial `config apply` or `model register`, even though Apply itself
// had already stopped saying it in the post-apply report. Approving a lie is
// worse than printing one.
func FilterChanges(changes []string, prune bool) []string {
	if prune {
		return changes
	}
	return slices.DeleteFunc(changes, func(c string) bool {
		return strings.HasPrefix(c, "- ")
	})
}

func Apply(ctx context.Context, m audit.Mutation, now time.Time, want *Snapshot, opt Options) (Result, error) {
	tx := m.Tx()
	have, err := Read(ctx, tx)
	if err != nil {
		return Result{}, err
	}
	res := Result{Changes: FilterChanges(Changes(have, want), opt.Prune)}

	// Nodes first: deployments reference them, and a node this control plane
	// has never met cannot be conjured by a file. A node joins by enrolling
	// (dev/specs/02-enrollment.md), and a configuration that could create one
	// would let a paste into the wrong terminal add a machine to the fleet.
	for _, n := range want.Nodes {
		var exists int
		if err := tx.QueryRowContext(ctx, `SELECT count(*) FROM node WHERE name = ?`, n.Name).
			Scan(&exists); err != nil {
			return res, err
		}
		if exists == 0 {
			return res, fmt.Errorf("%w %q: a node joins by enrolling, not by configuration", ErrUnknownNode, n.Name)
		}
		if _, err := tx.ExecContext(ctx,
			`UPDATE node SET state = ?, constraints_json = ?, reboot_policy = ? WHERE name = ?`,
			n.State, orDefault(n.Constraints, "{}"), n.RebootPolicy, n.Name); err != nil {
			return res, fmt.Errorf("updating node %q: %w", n.Name, err)
		}
	}

	if err := checkPolicy(ctx, tx, want); err != nil {
		return res, err
	}
	// Backends before models and deployments, both of which name one: a
	// document that registers a descriptor and uses it in the same apply has
	// to work, or registration is a two-step dance for no reason.
	if err := applyBackends(ctx, m, now, want, have, opt, &res); err != nil {
		return res, err
	}
	if err := applyModels(ctx, m, now, want, have, opt, &res); err != nil {
		return res, err
	}
	if err := applyDeployments(ctx, tx, now, want, have, opt, &res); err != nil {
		return res, err
	}
	if err := applyRoutes(ctx, tx, now, want, have, opt, &res); err != nil {
		return res, err
	}
	if err := applyLimits(ctx, tx, want, have, opt, &res); err != nil {
		return res, err
	}
	// Grants last: they reference routes, which applyRoutes has just created.
	if err := applyGrants(ctx, tx, now, want, have, opt, &res); err != nil {
		return res, err
	}
	// And every deletion after every creation, children before parents.
	if err := pruneAll(ctx, m, want, have, opt, &res); err != nil {
		return res, err
	}
	// Last, over whatever the document left standing: a member this apply
	// removed is not a member to refuse.
	if err := checkRouteDialects(ctx, tx); err != nil {
		return res, err
	}
	slices.Sort(res.Orphans)
	return res, nil
}

func applyModels(ctx context.Context, mut audit.Mutation, now time.Time, want, have *Snapshot, opt Options, res *Result) error {
	tx := mut.Tx()

	// Read once, and only when there is something to check: every apply passes
	// through here, most of them with no models in the document at all.
	var active policy.Profile
	if len(want.Models) > 0 {
		var err error
		if active, _, err = policy.Active(ctx, tx); err != nil {
			return fmt.Errorf("reading the active policy: %w", err)
		}
	}

	for _, m := range want.Models {
		// dev/specs/05-catalog.md §1: the artifact kind **must match the
		// backend's weights_layout**. Checked here because the alternative is
		// where it was found — an apply that succeeds, and then a node
		// reporting the model `corrupt` with "unknown weights layout", which
		// names neither the field nor the document that set it. A catalog entry
		// that can never stage is not a catalog entry.
		if err := checkArtifact(ctx, mut.Tx(), m); err != nil {
			return err
		}
		if err := checkOrigin(mut, active, m, have); err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO model
			(id, backend, source, artifact, origin_org, origin_country, license,
			 manifest_sha256, total_bytes, hints_json, manifest_body, created_at)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
			ON CONFLICT (id) DO UPDATE SET
				backend = excluded.backend, source = excluded.source, artifact = excluded.artifact,
				origin_org = excluded.origin_org, origin_country = excluded.origin_country,
				license = excluded.license, manifest_sha256 = excluded.manifest_sha256,
				total_bytes = excluded.total_bytes, hints_json = excluded.hints_json,
				manifest_body = excluded.manifest_body`,
			m.ID, m.Backend, m.Source, m.Artifact, nullable(m.OriginOrg), nullable(m.OriginCountry),
			nullable(m.License), nullable(m.ManifestSHA256), nullableInt(m.TotalBytes),
			orDefault(m.Hints, "{}"), nullable(m.ManifestBody), stamp(now)); err != nil {
			return fmt.Errorf("applying model %q: %w", m.ID, err)
		}
	}
	return nil
}

// checkOrigin refuses a model whose provenance the active profile denies.
//
// Here rather than in `model register`, because register is not the only way a
// model reaches the catalog: it builds a document and hands it to Apply, and so
// does `config apply` with one an operator wrote. A check in the verb would be
// a control with a documented bypass sitting next to it.
//
// **Only a new model, or one whose declared origin moved.** A profile tightened
// after a model was registered flags its deployments rather than stopping them
// (dev/specs/05-catalog.md §2, dev/specs/11-failure-modes.md), and refusing
// every later document that merely restates that model would stop them by
// another road: the operator could change nothing else in the fleet until they
// deleted it. `nodary policy apply` names what a candidate profile would deny,
// which is where that decision belongs and who should be making it.
func checkOrigin(mut audit.Mutation, active policy.Profile, want Model, have *Snapshot) error {
	for _, had := range have.Models {
		if had.ID == want.ID && had.OriginOrg == want.OriginOrg && had.OriginCountry == want.OriginCountry {
			return nil
		}
	}
	err := active.DeniesOrigin(want.OriginOrg, want.OriginCountry)
	if err == nil {
		return nil
	}
	// dev/specs/05-catalog.md §2: the rejection is recorded with the actor and
	// the attempted origin. The actor is a field of the record already; without
	// these the origin would exist only inside the error text, which is prose a
	// query cannot find. A rolled-back failure still carries them —
	// audit.Log.Act writes its record in a transaction of its own.
	mut.Detail("denied_model", want.ID)
	mut.Detail("denied_origin_org", want.OriginOrg)
	mut.Detail("denied_origin_country", want.OriginCountry)
	return fmt.Errorf("model %q: %w", want.ID, err)
}

func applyDeployments(ctx context.Context, tx *sql.Tx, now time.Time, want, have *Snapshot, opt Options, res *Result) error {
	for _, d := range want.Deployments {
		for _, ref := range []struct{ what, table, col, id string }{
			{"model", "model", "id", d.ModelID},
			{"node", "node", "name", d.NodeName},
		} {
			var exists int
			// The table and column are literals from this slice, never input.
			if err := tx.QueryRowContext(ctx,
				fmt.Sprintf(`SELECT count(*) FROM %s WHERE %s = ?`, ref.table, ref.col), ref.id).
				Scan(&exists); err != nil {
				return err
			}
			if exists == 0 {
				// "this control plane", not "this configuration": the check is
				// a query against the database, and a partial document —
				// which is the ordinary case, since --prune defaults off — is
				// meant to reference objects it does not restate. Sending an
				// operator back to their file to look for a node that is
				// missing from the *fleet* is the wrong direction.
				return fmt.Errorf("%w: deployment %q names %s %q, which this control plane does not have",
					ErrInvalid, d.ID, ref.what, ref.id)
			}
		}
		// Before the insert, so a deployment the backend cannot serve never
		// reaches the database and never reaches a node.
		if err := checkCapabilities(ctx, tx, d); err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO deployment
			(id, model_id, node_name, backend, image_digest, params_json, extra_args_json,
			 env_json, port, disabled, state, created_at, updated_at)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'defined', ?, ?)
			ON CONFLICT (id) DO UPDATE SET
				model_id = excluded.model_id, node_name = excluded.node_name,
				backend = excluded.backend, image_digest = excluded.image_digest,
				params_json = excluded.params_json,
				extra_args_json = excluded.extra_args_json, env_json = excluded.env_json,
				port = excluded.port, disabled = excluded.disabled,
				updated_at = excluded.updated_at`,
			d.ID, d.ModelID, d.NodeName, d.Backend, nullable(d.Image), orDefault(d.Params, "{}"),
			orDefault(d.ExtraArgs, "[]"), orDefault(d.Env, "{}"),
			nullableInt(int64(d.Port)), d.Disabled, stamp(now), stamp(now)); err != nil {
			return fmt.Errorf("applying deployment %q: %w", d.ID, err)
		}
		// The GPU claim is replaced wholesale. Deleting first is what lets a
		// deployment move from GPU 0 to GPU 1 without colliding with itself.
		if _, err := tx.ExecContext(ctx, `DELETE FROM deployment_gpu WHERE deployment_id = ?`, d.ID); err != nil {
			return err
		}
		for _, idx := range d.GPUs {
			if _, err := tx.ExecContext(ctx,
				`INSERT INTO deployment_gpu (deployment_id, node_name, gpu_index) VALUES (?, ?, ?)`,
				d.ID, d.NodeName, idx); err != nil {
				// The unique index in 0006_fleet.sql is the guard and stays
				// the guard. This turns what it says into something both front
				// ends can act on: raw, it reaches a person as "constraint
				// failed: UNIQUE constraint failed: deployment_gpu.node_name,
				// deployment_gpu.gpu_index (2067)" — naming neither the card
				// nor who holds it — and an API client as a 500 with the
				// message withheld, which is the same shape as the three
				// applier refusals R2-44 already found unwrapped.
				//
				// The lookup is safe inside the failed statement's
				// transaction: SQLite's default ON CONFLICT ABORT rolls back
				// the statement, not the transaction.
				var other string
				if e := tx.QueryRowContext(ctx,
					`SELECT deployment_id FROM deployment_gpu WHERE node_name = ? AND gpu_index = ?`,
					d.NodeName, idx).Scan(&other); e == nil && other != d.ID {
					return fmt.Errorf("%w: GPU %d on %s is already claimed by %q; a card serves "+
						"one deployment at a time. Give this one another (`model register --gpu`)",
						ErrInvalid, idx, d.NodeName, other)
				}
				return fmt.Errorf("claiming GPU %d on %s for %q: %w", idx, d.NodeName, d.ID, err)
			}
		}
	}
	if err := checkPorts(ctx, tx, want); err != nil {
		return err
	}
	return nil
}

// checkPorts refuses two deployments publishing the same loopback port on one
// node.
//
// **This had no guard at all, and `model register` defaults `--port` to 8001.**
// Registering a second model on a node without naming a port therefore produced
// two deployments both publishing 127.0.0.1:8001, which is not a loud failure:
// the second container fails to bind while the first keeps serving, so the
// gateway's route for the second model reaches the *first model's* server. A
// request for one model answered by another, metered against the wrong one.
// Two claims on one GPU is the analogous failure and 0006_fleet.sql guards it
// with a unique index; the port had nothing.
//
// A check here rather than an index, for two reasons. A partial unique index
// added now would fail to build on any database that already holds a duplicate
// pair — which is exactly the databases this bug has produced — leaving a
// control plane that cannot migrate. And ports have no racing second writer the
// way GPU claims do: `observed.Heartbeat` never touches the column, so every
// write of it passes through here, inside the write transaction, on the single
// writer connection.
//
// After the inserts rather than before each one, so that two deployments
// *exchanging* ports in one document is applied rather than refused for a
// collision that exists only halfway through the loop.
func checkPorts(ctx context.Context, tx *sql.Tx, want *Snapshot) error {
	for _, d := range want.Deployments {
		if d.Port <= 0 {
			continue
		}
		var other string
		err := tx.QueryRowContext(ctx,
			`SELECT id FROM deployment WHERE node_name = ? AND port = ? AND id <> ? ORDER BY id LIMIT 1`,
			d.NodeName, d.Port, d.ID).Scan(&other)
		if errors.Is(err, sql.ErrNoRows) {
			continue
		}
		if err != nil {
			return err
		}
		return fmt.Errorf("%w: deployment %q publishes port %d on %s, which %q already publishes: "+
			"two servers on one loopback port means the second never binds and the gateway "+
			"answers for the first. Give one of them another port (`model register --port`)",
			ErrInvalid, d.ID, d.Port, d.NodeName, other)
	}
	return nil
}

// applyGrants replaces the per-user route allowlist wholesale.
//
// Wholesale, and not a merge: this is an allowlist, and the operation an
// administrator most needs to be able to perform on one is *removal*. A merge
// that only ever added would make revoking access something `config apply`
// could not express, which is the one direction that has to work.
// applyGrants adds what the document grants and reports what it does not
// mention, like every other object here.
//
// **It used to begin `DELETE FROM user_route`, unconditionally.** That made any
// partial apply — a new model, a changed port, anything — revoke every user's
// access to every route, and the deletion was invisible: with prune off, Apply
// strips the `- ` lines from the change list, so the verb reported adding a
// model and said nothing about the access it had just destroyed. The symptom is
// 403 on a fleet where nothing else changed, and dev/specs/06-gateway.md §2's
// deny-by-default means nobody can tell that from correct behavior.
//
// Removing a grant is therefore `--prune`, which is how everything else in this
// file is removed.
func applyGrants(ctx context.Context, tx *sql.Tx, now time.Time, want, have *Snapshot, opt Options, res *Result) error {
	for _, g := range want.Grants {
		var userID string
		err := tx.QueryRowContext(ctx, `SELECT id FROM user WHERE name = ?`, g.User).Scan(&userID)
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("%w: grant names user %q, which does not exist", ErrInvalid, g.User)
		}
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx,
			`INSERT INTO user_route (user_id, route_name, granted_at) VALUES (?, ?, ?)
			 ON CONFLICT (user_id, route_name) DO NOTHING`,
			userID, g.Route, stamp(now)); err != nil {
			return fmt.Errorf("granting %s access to %s: %w", g.User, g.Route, err)
		}
	}
	for _, g := range have.Grants {
		if slices.Contains(want.Grants, g) {
			continue
		}
		// The same key the diff uses, so "left in place" and "- grant" name
		// the thing the same way.
		key := g.User + " → " + g.Route
		if !opt.Prune {
			res.Orphans = append(res.Orphans, "grant "+key)
			continue
		}
		if _, err := tx.ExecContext(ctx,
			`DELETE FROM user_route WHERE route_name = ?
			   AND user_id = (SELECT id FROM user WHERE name = ?)`, g.Route, g.User); err != nil {
			return err
		}
		res.Changes = append(res.Changes, "- grant "+key)
	}
	return nil
}

func applyRoutes(ctx context.Context, tx *sql.Tx, now time.Time, want, have *Snapshot, opt Options, res *Result) error {
	for _, r := range want.Routes {
		if _, err := tx.ExecContext(ctx,
			`INSERT INTO route (name, strategy, created_at) VALUES (?, ?, ?)
			 ON CONFLICT (name) DO UPDATE SET strategy = excluded.strategy`,
			r.Name, orDefault(r.Strategy, "round-robin"), stamp(now)); err != nil {
			return fmt.Errorf("applying route %q: %w", r.Name, err)
		}
		if _, err := tx.ExecContext(ctx, `DELETE FROM route_member WHERE route_name = ?`, r.Name); err != nil {
			return err
		}
		for _, mem := range r.Members {
			w := mem.Weight
			if w == 0 {
				w = 1
			}
			// Checked before the insert so the refusal names the file's
			// mistake. The foreign key would catch it either way, but
			// "FOREIGN KEY constraint failed (787)" is not something to hand
			// somebody who just edited a TOML file.
			var exists int
			if err := tx.QueryRowContext(ctx,
				`SELECT count(*) FROM deployment WHERE id = ?`, mem.DeploymentID).Scan(&exists); err != nil {
				return err
			}
			if exists == 0 {
				return fmt.Errorf("%w: route %q names deployment %q, which this control plane does not have",
					ErrInvalid, r.Name, mem.DeploymentID)
			}
			if _, err := tx.ExecContext(ctx,
				`INSERT INTO route_member (route_name, deployment_id, weight) VALUES (?, ?, ?)`,
				r.Name, mem.DeploymentID, w); err != nil {
				return fmt.Errorf("adding %q to route %q: %w", mem.DeploymentID, r.Name, err)
			}
		}
	}
	return nil
}

// applyBackends registers and removes operator descriptors — 04 §9.
//
// Three refusals, each of which is the whole reason this is not a plain
// upsert.
//
// **A descriptor that does not parse never lands.** §9 says registration
// validates against the schema and rejects unknown keys, and doing it here
// rather than in the verb means `config apply` cannot be the way around it —
// the same argument R4-32 makes for checking provenance in applyModels rather
// than in `model register`.
//
// **A registered name may not shadow a built-in.** An operator who redefined
// `vllm` would silently change the meaning of every deployment already using
// it, on the next reconcile, with nothing in the change list saying so.
//
// **Removal is refused while a deployment references it.** A node whose
// descriptor vanished cannot render an argv at all, so what an operator would
// see is every deployment on that backend failing at once for a reason that
// names neither this document nor this line.
func applyBackends(ctx context.Context, mut audit.Mutation, now time.Time,
	want, have *Snapshot, opt Options, res *Result) error {

	tx := mut.Tx()
	// 04 §9: the record carries the descriptor's digest. The revision holds
	// the bytes, but a digest in the audit record is what an assessor can
	// query for without decoding a snapshot — and it is the same digest the
	// node is sent and reports back, so the three can be held to each other.
	// Set at the end rather than deferred: a detail survives the rollback of
	// the transaction it was added in (audit.Log.Act writes its record in one
	// of its own), so recording a digest on the way out of a failure would
	// state that something was registered which was not.
	registered := map[string]string{}

	// The profile's gates (04 §5, 07 §1). Read here rather than passed in,
	// because every road into this function has to meet them.
	var active policy.Profile
	if len(want.Backends) > 0 {
		var err error
		if active, _, err = policy.Active(ctx, tx); err != nil {
			return err
		}
	}

	for _, b := range want.Backends {
		d, err := backend.Parse([]byte(b.Source))
		if err != nil {
			return fmt.Errorf("%w: backend %q: %v", ErrInvalid, b.Name, err)
		}
		// The name in the document and the name inside the descriptor are two
		// places one fact can be written, so they are held to each other
		// rather than one silently winning.
		if d.Backend.Name != b.Name {
			return fmt.Errorf("%w: backend %q declares itself %q; the document and the "+
				"descriptor have to agree on the name", ErrInvalid, b.Name, d.Backend.Name)
		}
		if _, builtin := builtins()[b.Name]; builtin {
			return fmt.Errorf("%w: %q is built into this binary and cannot be redefined; "+
				"a registered descriptor with that name would change what every deployment "+
				"already using it means", ErrInvalid, b.Name)
		}
		// A derive of a parent this build has not got is refused here rather
		// than becoming a row nothing can resolve: the descriptor parses, so
		// nothing later would call it malformed — it would simply have no
		// vocabulary, and every deployment on it would fail for the wrong
		// reason.
		if _, err := backend.Resolve(d); err != nil {
			return fmt.Errorf("%w: backend %q: %v", ErrInvalid, b.Name, err)
		}
		// **A derive is gated by allow_derived_images, not by
		// allow_custom_backends**, and §5 says so in as many words: the two
		// settings are consistent because "registering an arbitrary backend
		// introduces unreviewed argument handling and a new weight layout,
		// while a derive changes an image and inherits everything else".
		// Holding a derive to the custom-backend gate made derived images
		// unreachable under `regulated` — the one profile §5 argues needs
		// them, since a FIPS override is the motivating case.
		if dv := d.Backend.Derive; dv != nil {
			if !active.AllowDerivedImages {
				return fmt.Errorf("%w: the %s profile does not allow derived images; %q "+
					"declares [backend.derive]", ErrInvalid, active.Name, b.Name)
			}
			if active.RequirePinnedDerives {
				if err := dv.Pinned(); err != nil {
					return fmt.Errorf("%w: backend %q: %v", ErrInvalid, b.Name, err)
				}
			}
		} else if !active.AllowCustomBackends {
			return fmt.Errorf("%w: the %s profile does not allow custom backends; "+
				"this build serves %s", ErrInvalid, active.Name, strings.Join(builtinNames(), ", "))
		}
		sum := sha256.Sum256([]byte(b.Source))
		registered[b.Name] = hex.EncodeToString(sum[:])
		if _, err := tx.ExecContext(ctx, `INSERT INTO backend
			(name, body, sha256, created_at, updated_at) VALUES (?, ?, ?, ?, ?)
			ON CONFLICT (name) DO UPDATE SET
				body = excluded.body, sha256 = excluded.sha256,
				updated_at = excluded.updated_at`,
			b.Name, b.Source, hex.EncodeToString(sum[:]), stamp(now), stamp(now)); err != nil {
			return fmt.Errorf("registering backend %q: %w", b.Name, err)
		}
	}

	if len(registered) > 0 {
		mut.Detail("backends_registered", registered)
	}
	return nil
}

// pruneBackends is applyBackends' other half, run from pruneAll rather than
// beside the registrations — a backend and the last deployment using it have
// to be removable in one document, and checking "still used" before the
// deployment prune ran made that refuse.
func pruneBackends(ctx context.Context, mut audit.Mutation, want, have *Snapshot,
	opt Options, res *Result) error {

	tx := mut.Tx()
	var removed []string
	for _, b := range have.Backends {
		if slices.ContainsFunc(want.Backends, func(x Backend) bool { return x.Name == b.Name }) {
			continue
		}
		if !opt.Prune {
			res.Orphans = append(res.Orphans, "backend "+b.Name)
			continue
		}
		var used string
		err := tx.QueryRowContext(ctx,
			`SELECT id FROM deployment WHERE backend = ? ORDER BY id LIMIT 1`, b.Name).Scan(&used)
		if err == nil {
			return fmt.Errorf("%w: backend %q is still used by deployment %q; a node whose "+
				"descriptor vanished cannot render an argv at all", ErrInvalid, b.Name, used)
		}
		if !errors.Is(err, sql.ErrNoRows) {
			return err
		}
		if _, err := tx.ExecContext(ctx, `DELETE FROM backend WHERE name = ?`, b.Name); err != nil {
			return err
		}
		removed = append(removed, b.Name)
		res.Changes = append(res.Changes, "- backend "+b.Name)
	}
	if len(removed) > 0 {
		mut.Detail("backends_removed", removed)
	}
	return nil
}

// pruneAll deletes what the configuration no longer names, children first.
//
// **Separate from the upserts, and in the opposite order.** Creating needs a
// model before the deployment that references it; deleting needs the reverse,
// and pruning inside each applyX did it in creation order — so `config apply
// --prune` could not remove a model at all. It deleted the model row while the
// deployment still pointed at it and came back with SQLite's own
// `FOREIGN KEY constraint failed (787)`, which is not even a refusal: nothing
// wraps it, so an API client got a 500 with the message withheld.
func pruneAll(ctx context.Context, mut audit.Mutation, want, have *Snapshot,
	opt Options, res *Result) error {

	tx := mut.Tx()
	if err := prune(ctx, tx, "route", "name", names(have.Routes, func(r Route) string { return r.Name }),
		names(want.Routes, func(r Route) string { return r.Name }), opt, res); err != nil {
		return err
	}
	if err := prune(ctx, tx, "deployment", "id", names(have.Deployments, func(d Deployment) string { return d.ID }),
		names(want.Deployments, func(d Deployment) string { return d.ID }), opt, res); err != nil {
		return err
	}
	if err := prune(ctx, tx, "model", "id", names(have.Models, func(m Model) string { return m.ID }),
		names(want.Models, func(m Model) string { return m.ID }), opt, res); err != nil {
		return err
	}
	return pruneBackends(ctx, mut, want, have, opt, res)
}

// checkPolicy refuses a document that would move the posture.
//
// **Changes() reported `~ policy default -> regulated` and Apply did nothing
// about it.** So a document that tightened the profile previewed as though it
// would, recorded a revision saying it had, and left the posture where it was
// — which for a product whose deliverable is a chain an assessor reads is the
// worst shape a bug can take: not silence, but a confident claim that the
// thing happened.
//
// Refused rather than applied, and that is the point rather than the cheap way
// out. `nodary policy apply` shows what a profile *loosens* before the
// confirmation ([07 §4](dev/specs/07-identity-audit.md) requires loosening
// not to be silent) and what it would *deny* among models already registered
// (05 §2). A posture that moved as a side effect of a configuration apply
// would have had neither in front of the person agreeing to it.
//
// A document carrying the profile that is already active passes, because that
// is what `config export` writes and an export has to round-trip.
func checkPolicy(ctx context.Context, q Querier, want *Snapshot) error {
	if want.Policy == nil {
		return nil
	}
	active, source, err := policy.Active(ctx, q)
	if err != nil {
		return err
	}
	if want.Policy.Name == active.Name && want.Policy.Source == string(source) {
		return nil
	}
	return fmt.Errorf("%w: this document sets the policy profile to %q and %q is active. "+
		"A posture change is `nodary policy apply`, which shows what it loosens and what it "+
		"would deny before you agree to it; `config apply` carries the profile so that an "+
		"export round-trips, and will not move it",
		ErrInvalid, want.Policy.Name, active.Name)
}

// BackendFor resolves a backend name to the descriptor in force.
//
// Built-ins first, and not only because it is cheaper: a registered descriptor
// may not take a built-in's name, so checking here in this order makes that
// refusal belt-and-braces rather than the only thing standing between an
// operator and redefining `vllm` for a fleet that is already running it.
//
// It lives in this package rather than in internal/backend because the
// registry is a table and internal/backend has no database — and giving it one
// would make a descriptor parser depend on a schema.
func BackendFor(ctx context.Context, q Querier, name string) (backend.Descriptor, error) {
	if d, ok := builtins()[name]; ok {
		return d, nil
	}
	var body string
	err := q.QueryRowContext(ctx, `SELECT body FROM backend WHERE name = ?`, name).Scan(&body)
	if errors.Is(err, sql.ErrNoRows) {
		return backend.Get(name) // for its message, which names what this build has
	}
	if err != nil {
		return backend.Descriptor{}, err
	}
	d, err := backend.Parse([]byte(body))
	if err != nil {
		return backend.Descriptor{}, err
	}
	return backend.Resolve(d)
}

// BackendReports is every backend in force, built-in and registered, as the
// projection both front ends render.
//
// Here rather than in internal/backend for the same reason BackendFor is: the
// registry is a table, and only this package can read one.
func BackendReports(ctx context.Context, q Querier) ([]backend.Report, error) {
	all := builtins()
	out := make([]backend.Report, 0, len(all))
	for _, n := range backend.Names(all) {
		out = append(out, backend.NewReport(all[n], backend.SourceBuiltIn, ""))
	}
	rows, err := q.QueryContext(ctx, `SELECT name, body, sha256 FROM backend ORDER BY name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		var name, body, sum string
		if err := rows.Scan(&name, &body, &sum); err != nil {
			return nil, err
		}
		d, err := backend.Parse([]byte(body))
		if err != nil {
			// Reported rather than hidden: a row that no longer parses is one
			// an operator has to see, and it is exactly the row whose
			// deployments are failing.
			out = append(out, backend.Report{Name: name, Source: backend.SourceRegistered,
				SHA256: sum, API: "unreadable: " + err.Error()})
			continue
		}
		if d, err = backend.Resolve(d); err != nil {
			out = append(out, backend.Report{Name: name, Source: backend.SourceRegistered,
				SHA256: sum, API: "unreadable: " + err.Error()})
			continue
		}
		out = append(out, backend.NewReport(d, backend.SourceRegistered, sum))
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	built, err := builtImages(ctx, q)
	if err != nil {
		return nil, err
	}
	for i := range out {
		out[i].Built = built[out[i].Name]
		out[i].Built.Staleness(out[i].Recipe)
	}
	return out, nil
}

// BackendReport is one of them.
func BackendReport(ctx context.Context, q Querier, name string) (backend.Report, error) {
	if d, ok := builtins()[name]; ok {
		return backend.NewReport(d, backend.SourceBuiltIn, ""), nil
	}
	var body, sum string
	err := q.QueryRowContext(ctx,
		`SELECT body, sha256 FROM backend WHERE name = ?`, name).Scan(&body, &sum)
	if errors.Is(err, sql.ErrNoRows) {
		_, err := backend.Get(name)
		return backend.Report{}, err
	}
	if err != nil {
		return backend.Report{}, err
	}
	d, err := backend.Parse([]byte(body))
	if err != nil {
		return backend.Report{}, err
	}
	if d, err = backend.Resolve(d); err != nil {
		return backend.Report{}, err
	}
	r := backend.NewReport(d, backend.SourceRegistered, sum)
	if r.Built, err = BuiltImage(ctx, q, name); err != nil {
		return backend.Report{}, err
	}
	r.Built.Staleness(r.Recipe)
	return r, nil
}

// builtins and builtinNames are the compiled-in set, tolerating the error: a
// build whose own descriptors do not parse fails its own tests, and refusing
// every apply here would turn that into an outage.
func builtins() map[string]backend.Descriptor {
	all, err := backend.Builtins()
	if err != nil {
		return nil
	}
	return all
}

func builtinNames() []string { return backend.Names(builtins()) }

func applyLimits(ctx context.Context, tx *sql.Tx, want, have *Snapshot, opt Options, res *Result) error {
	for _, l := range want.Limits {
		if _, err := tx.ExecContext(ctx, `INSERT INTO limits
			(subject_kind, subject_id, rpm, tpm, daily_tokens, max_concurrent)
			VALUES (?, ?, ?, ?, ?, ?)
			ON CONFLICT (subject_kind, subject_id) DO UPDATE SET
				rpm = excluded.rpm, tpm = excluded.tpm,
				daily_tokens = excluded.daily_tokens, max_concurrent = excluded.max_concurrent`,
			l.SubjectKind, l.SubjectID, nullableInt(int64(l.RPM)), nullableInt(int64(l.TPM)),
			nullableInt(int64(l.DailyTokens)), nullableInt(int64(l.MaxConcurrent))); err != nil {
			return fmt.Errorf("applying limits for %s/%s: %w", l.SubjectKind, l.SubjectID, err)
		}
	}
	for _, l := range have.Limits {
		if slices.ContainsFunc(want.Limits, func(x Limit) bool {
			return x.SubjectKind == l.SubjectKind && x.SubjectID == l.SubjectID
		}) {
			continue
		}
		key := l.SubjectKind + "/" + l.SubjectID
		if !opt.Prune {
			res.Orphans = append(res.Orphans, "limits "+key)
			continue
		}
		if _, err := tx.ExecContext(ctx,
			`DELETE FROM limits WHERE subject_kind = ? AND subject_id = ?`, l.SubjectKind, l.SubjectID); err != nil {
			return err
		}
		res.Changes = append(res.Changes, "- limits "+key)
	}
	return nil
}

// prune removes objects absent from the configuration, or reports them.
//
// The table and key names reach a Sprintf. They are compile-time literals from
// the three call sites in this file and never touch anything a caller supplied;
// the values are still bound as parameters. Said out loud because the shape is
// the one that is usually a defect.
func prune(ctx context.Context, tx *sql.Tx, table, key string, have, want []string, opt Options, res *Result) error {
	for _, id := range have {
		if slices.Contains(want, id) {
			continue
		}
		if !opt.Prune {
			res.Orphans = append(res.Orphans, table+" "+id)
			continue
		}
		for _, dep := range dependents[table] {
			if _, err := tx.ExecContext(ctx,
				fmt.Sprintf(`DELETE FROM %s WHERE %s = ?`, dep.table, dep.column), id); err != nil {
				return fmt.Errorf("pruning %s %q: clearing %s: %w", table, id, dep.table, err)
			}
		}
		if _, err := tx.ExecContext(ctx,
			fmt.Sprintf(`DELETE FROM %s WHERE %s = ?`, table, key), id); err != nil {
			return fmt.Errorf("pruning %s %q: %w", table, id, err)
		}
	}
	return nil
}

// dependents hang off a configured object without being configuration.
//
// **They are deliberately not ON DELETE CASCADE.** A staging row is an
// observation and a reset or restart row is an instruction somebody issued;
// neither should disappear because an unrelated write touched its parent, and
// the foreign key is what says so. But they also cannot outlive the object
// they are about — and because they did, a model that had ever been staged
// could never be pruned: `config apply --prune` failed on the `staging` row
// with SQLite's own foreign-key error, for every model an agent had reported.
//
// Cleared here rather than at each call site so a table added later has one
// place to be listed, which is the same argument prune itself makes. The names
// are compile-time literals from this map; the ids are still bound.
var dependents = map[string][]struct{ table, column string }{
	"model": {
		{"staging", "model_id"},
		{"stage_reset", "model_id"},
	},
	"deployment": {
		{"deployment_restart", "deployment_id"},
	},
}

func names[T any](in []T, key func(T) string) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = key(v)
	}
	return out
}

func stamp(t time.Time) string { return t.UTC().Truncate(time.Millisecond).Format(audit.TimeFormat) }

func orDefault(s, d string) string {
	if s == "" {
		return d
	}
	return s
}

func nullableInt(n int64) any {
	if n == 0 {
		return nil
	}
	return n
}

// checkRouteDialects refuses a route carrying a deployment the gateway cannot
// proxy — dev/specs/04-backends.md §8.
//
// `api` is what tells the control plane whether it may route to a deployment
// directly, and the gateway hands LiteLLM `openai/<model>` for every member it
// renders (internal/gateway/litellm.go). So a `triton` or `custom` deployment
// on a route is not a failure anybody sees as one: the proxy accepts the
// configuration, comes up healthy, and answers every request by speaking
// OpenAI at a server that does not speak it.
//
// **Over every member, at the end, rather than beside the insert.** Two
// different documents produce this state — one that adds a member to a route,
// and one that re-registers a backend under the same name with a different
// `api` — and a check inside applyRoutes would miss the second entirely,
// because that document names no route at all. Backends have been registrable
// since R6-07, so the second is a road an operator now has.
//
// An unknown backend is left alone for the reason checkArtifact gives: R6 owns
// which backends exist, and refusing here would make this a second place that
// decides.
func checkRouteDialects(ctx context.Context, tx *sql.Tx) error {
	type member struct{ route, deployment, backend string }

	// Read out before resolving any of them: a Querier call while these rows
	// are open would be a second statement on the transaction's one
	// connection.
	var members []member
	rows, err := tx.QueryContext(ctx,
		`SELECT rm.route_name, rm.deployment_id, d.backend
		   FROM route_member rm JOIN deployment d ON d.id = rm.deployment_id
		  ORDER BY rm.route_name, rm.deployment_id`)
	if err != nil {
		return err
	}
	for rows.Next() {
		var m member
		if err := rows.Scan(&m.route, &m.deployment, &m.backend); err != nil {
			rows.Close()
			return err
		}
		members = append(members, m)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return err
	}
	rows.Close()

	dialect := map[string]string{}
	for _, m := range members {
		api, seen := dialect[m.backend]
		if !seen {
			d, err := BackendFor(ctx, tx, m.backend)
			if err != nil {
				dialect[m.backend] = ""
				continue
			}
			api = d.Backend.API
			dialect[m.backend] = api
		}
		if api == "" || api == "openai" {
			continue
		}
		return fmt.Errorf("%w: route %q carries deployment %q, whose backend %q speaks %q and "+
			"not openai; every member is proxied as OpenAI, so this route would answer each "+
			"request by speaking a dialect the server does not. 04 §8 reaches one through an "+
			"adapter configured for it, and this build has no way to configure one",
			ErrInvalid, m.route, m.deployment, m.backend, api)
	}
	return nil
}

// checkCapabilities refuses a deployment asking its backend for something the
// descriptor says it cannot do — dev/specs/04-backends.md §7.
//
// Here rather than only on the node, which is the point of the task: the agent
// refuses an unrenderable deployment too, but a minute later and on a GPU host,
// so what an operator sees is a change that was accepted and then did not
// happen. An unknown backend is left alone for the reason checkArtifact gives.
//
// Wrapped in ErrInvalid rather than returned as backend.ErrUnsupported,
// because that is the sentinel both front ends already answer identically —
// exit 1 and a 422 naming the refusal. An unwrapped one reaches an API client
// as a 500 with the message withheld, which is the shape this milestone's
// predecessor found five times.
func checkCapabilities(ctx context.Context, q Querier, d Deployment) error {
	desc, err := BackendFor(ctx, q, d.Backend)
	if err != nil {
		return nil
	}
	p := backend.Params{}
	if d.Params != "" {
		if err := json.Unmarshal([]byte(d.Params), &p); err != nil {
			return fmt.Errorf("%w: deployment %q has params that are not a JSON object: %v",
				ErrInvalid, d.ID, err)
		}
	}
	if err := desc.CheckParams(p, len(d.GPUs)); err != nil {
		return fmt.Errorf("%w: deployment %q: %s", ErrInvalid, d.ID, unwrapMessage(err))
	}
	return nil
}

// unwrapMessage drops the sentinel's own prose, which is a category and not a
// sentence: "the backend does not support this: llama-cpp does not support
// tensor parallelism" says it twice.
func unwrapMessage(err error) string {
	msg := err.Error()
	if _, rest, ok := strings.Cut(msg, ": "); ok {
		return rest
	}
	return msg
}

// checkArtifact refuses a model whose artifact kind its backend cannot read.
//
// The backend is the authority: each descriptor declares one `weights_layout`,
// and a model staged in another one is weights the server will not find. An
// unknown backend is left alone — R6 owns which backends exist, and refusing
// here would make this the second place that decides.
func checkArtifact(ctx context.Context, q Querier, m Model) error {
	d, err := BackendFor(ctx, q, m.Backend)
	if err != nil {
		return nil
	}
	if m.Artifact == "" || m.Artifact == d.Backend.WeightsLayout {
		return nil
	}
	return fmt.Errorf("%w: model %q is %q and the %s backend reads %q; "+
		"05 §1 requires the artifact kind to match the backend's weights_layout",
		ErrInvalid, m.ID, m.Artifact, m.Backend, d.Backend.WeightsLayout)
}

// DeniedModel is a catalog entry an origin policy refuses, with what is
// currently serving it.
type DeniedModel struct {
	ID          string   `json:"id"`
	Origin      string   `json:"origin"`
	Deployments []string `json:"deployments"`
}

// Denied names the models a profile's origin lists would refuse, and the
// deployments that would be left serving them.
//
// dev/specs/05-catalog.md §2 and dev/specs/11-failure-modes.md: tightening a
// policy under a registered model **flags** it rather than stopping it, because
// pulling a serving model out from under its users is a decision an operator
// makes, not one a configuration change makes for them. Flagged has to mean
// somewhere an operator actually looks, and the moment they are deciding is
// when they apply the profile — so this goes in `policy apply`'s preview, where
// it is part of what they attest to rather than a line they scroll past.
//
// Computed rather than stored. A column would have to be kept in step with
// every policy change and would be wrong the moment a profile loosened again;
// the origin and the profile are both already here.
func Denied(ctx context.Context, q Querier, p policy.Profile) ([]DeniedModel, error) {
	snap, err := Read(ctx, q)
	if err != nil {
		return nil, err
	}
	var out []DeniedModel
	for _, m := range snap.Models {
		if p.DeniesOrigin(m.OriginOrg, m.OriginCountry) == nil {
			continue
		}
		d := DeniedModel{ID: m.ID, Origin: originOf(m), Deployments: []string{}}
		for _, dep := range snap.Deployments {
			if dep.ModelID == m.ID {
				d.Deployments = append(d.Deployments, dep.ID)
			}
		}
		out = append(out, d)
	}
	return out, nil
}

func originOf(m Model) string {
	switch {
	case m.OriginOrg != "" && m.OriginCountry != "":
		return m.OriginOrg + " (" + m.OriginCountry + ")"
	case m.OriginOrg != "":
		return m.OriginOrg
	case m.OriginCountry != "":
		return m.OriginCountry
	default:
		return "undeclared"
	}
}

// SetDisabled flips the deployments of a model, optionally narrowed to one
// node, and reports how many it matched.
//
// Shared by `nodary model enable|disable` and POST /models/{id}/enable|disable
// so the two front ends cannot disagree about which deployments a verb touches
// — the constraint dev/tasks/README.md makes non-negotiable.
//
// **Every matching deployment, not one row.** deployment.id is the only primary
// key, so nothing stops two deployments of one model on one node; treating
// (model, node) as naming a single row would silently leave a replica running
// that an operator believed they had stopped.
func SetDisabled(snap *Snapshot, modelID, node string, disabled bool) (matched int) {
	for i := range snap.Deployments {
		if snap.Deployments[i].ModelID != modelID {
			continue
		}
		if node != "" && snap.Deployments[i].NodeName != node {
			continue
		}
		snap.Deployments[i].Disabled = disabled
		matched++
	}
	return matched
}

// BuiltImage is what `nodary backend build` left for one derive, nil if nothing
// has been built for it.
//
// In this package rather than internal/backend for BackendFor's reason: the
// record is a table, and a descriptor parser with a schema is a descriptor
// parser that cannot be tested without one.
func BuiltImage(ctx context.Context, q Querier, name string) (*backend.Built, error) {
	var b backend.Built
	err := q.QueryRowContext(ctx, `SELECT image, digest, base_digest, recipe_sha256,
		built_at, built_by FROM derived_image WHERE name = ?`, name).
		Scan(&b.Image, &b.Digest, &b.BaseDigest, &b.RecipeSHA256, &b.BuiltAt, &b.BuiltBy)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &b, nil
}

// builtImages is every one of them, for the listing.
func builtImages(ctx context.Context, q Querier) (map[string]*backend.Built, error) {
	rows, err := q.QueryContext(ctx, `SELECT name, image, digest, base_digest, recipe_sha256,
		built_at, built_by FROM derived_image`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := map[string]*backend.Built{}
	for rows.Next() {
		var name string
		var b backend.Built
		if err := rows.Scan(&name, &b.Image, &b.Digest, &b.BaseDigest, &b.RecipeSHA256,
			&b.BuiltAt, &b.BuiltBy); err != nil {
			return nil, err
		}
		out[name] = &b
	}
	return out, rows.Err()
}
