package config

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/nodarynet/nodary/internal/audit"
	"github.com/nodarynet/nodary/internal/backend"
)

// ErrUnknownNode is returned when a configuration names a node that has never
// enrolled.
var ErrUnknownNode = errors.New("unknown node")

// Result says what an apply did, so a caller can report it and a --dry-run can
// report it without doing it.
type Result struct {
	Changes []string
	// Orphans are objects in the database and absent from the configuration.
	// They are left alone unless Prune is set — see Options.
	Orphans []string
}

// Options controls an apply.
type Options struct {
	// Prune deletes objects the configuration does not mention.
	//
	// Off by default, and that default is the whole decision: the alternative
	// makes `config apply -f partial.toml` a fleet-wide delete, and the first
	// person to run it against a hand-written fragment loses their deployments.
	// Reconcile-to-absent assumes the file was generated by the same system,
	// which `config export` produces and a human writing a fragment does not.
	Prune bool
}

// Apply writes a snapshot into the database.
//
// One applier, three entrances: `config apply -f`, `config rollback`, and the
// tests. If rollback had its own it would be the one that drifts, and the drift
// would surface as "the rollback did not restore what export said was there" —
// discovered during a recovery, which is the worst possible time.
func Apply(ctx context.Context, m audit.Mutation, now time.Time, want *Snapshot, opt Options) (Result, error) {
	tx := m.Tx()
	have, err := Read(ctx, tx)
	if err != nil {
		return Result{}, err
	}
	res := Result{Changes: Changes(have, want)}
	if !opt.Prune {
		// **A `-` line is a deletion, and with prune off no deletion happens.**
		// Those objects are Orphans, reported separately as left in place.
		// Leaving them in the change list makes an ordinary partial apply say
		// it removed the node the operator is standing on — which is the most
		// alarming thing this verb could say untruthfully, and it said it every
		// time somebody applied a fragment.
		//
		// The prune path appends its own `-` lines below, as it deletes, so
		// what survives here is what was actually done.
		res.Changes = slices.DeleteFunc(res.Changes, func(c string) bool {
			return strings.HasPrefix(c, "- ")
		})
	}

	// Nodes first: deployments reference them, and a node this control plane
	// has never met cannot be conjured by a file. A node joins by enrolling
	// (docs/specs/02-enrollment.md), and a configuration that could create one
	// would let a paste into the wrong terminal add a machine to the fleet.
	for _, n := range want.Nodes {
		var exists int
		if err := tx.QueryRowContext(ctx, `SELECT count(*) FROM node WHERE name = ?`, n.Name).
			Scan(&exists); err != nil {
			return res, err
		}
		if exists == 0 {
			return res, fmt.Errorf("%w %q: a node joins by enrolling, not by configuration", ErrUnknownNode, n.Name)
		}
		if _, err := tx.ExecContext(ctx,
			`UPDATE node SET state = ?, constraints_json = ?, reboot_policy = ? WHERE name = ?`,
			n.State, orDefault(n.Constraints, "{}"), n.RebootPolicy, n.Name); err != nil {
			return res, fmt.Errorf("updating node %q: %w", n.Name, err)
		}
	}

	if err := applyModels(ctx, tx, now, want, have, opt, &res); err != nil {
		return res, err
	}
	if err := applyDeployments(ctx, tx, now, want, have, opt, &res); err != nil {
		return res, err
	}
	if err := applyRoutes(ctx, tx, now, want, have, opt, &res); err != nil {
		return res, err
	}
	if err := applyLimits(ctx, tx, want, have, opt, &res); err != nil {
		return res, err
	}
	// Grants last: they reference routes, which applyRoutes has just created.
	if err := applyGrants(ctx, tx, now, want, have, opt, &res); err != nil {
		return res, err
	}
	slices.Sort(res.Orphans)
	return res, nil
}

func applyModels(ctx context.Context, tx *sql.Tx, now time.Time, want, have *Snapshot, opt Options, res *Result) error {
	for _, m := range want.Models {
		// docs/specs/05-catalog.md §1: the artifact kind **must match the
		// backend's weights_layout**. Checked here because the alternative is
		// where it was found — an apply that succeeds, and then a node
		// reporting the model `corrupt` with "unknown weights layout", which
		// names neither the field nor the document that set it. A catalog entry
		// that can never stage is not a catalog entry.
		if err := checkArtifact(m); err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO model
			(id, backend, source, artifact, origin_org, origin_country, license,
			 manifest_sha256, total_bytes, hints_json, created_at)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
			ON CONFLICT (id) DO UPDATE SET
				backend = excluded.backend, source = excluded.source, artifact = excluded.artifact,
				origin_org = excluded.origin_org, origin_country = excluded.origin_country,
				license = excluded.license, manifest_sha256 = excluded.manifest_sha256,
				total_bytes = excluded.total_bytes, hints_json = excluded.hints_json`,
			m.ID, m.Backend, m.Source, m.Artifact, nullable(m.OriginOrg), nullable(m.OriginCountry),
			nullable(m.License), nullable(m.ManifestSHA256), nullableInt(m.TotalBytes),
			orDefault(m.Hints, "{}"), stamp(now)); err != nil {
			return fmt.Errorf("applying model %q: %w", m.ID, err)
		}
	}
	return prune(ctx, tx, "model", "id", names(have.Models, func(m Model) string { return m.ID }),
		names(want.Models, func(m Model) string { return m.ID }), opt, res)
}

func applyDeployments(ctx context.Context, tx *sql.Tx, now time.Time, want, have *Snapshot, opt Options, res *Result) error {
	for _, d := range want.Deployments {
		for _, ref := range []struct{ what, table, col, id string }{
			{"model", "model", "id", d.ModelID},
			{"node", "node", "name", d.NodeName},
		} {
			var exists int
			// The table and column are literals from this slice, never input.
			if err := tx.QueryRowContext(ctx,
				fmt.Sprintf(`SELECT count(*) FROM %s WHERE %s = ?`, ref.table, ref.col), ref.id).
				Scan(&exists); err != nil {
				return err
			}
			if exists == 0 {
				// "this control plane", not "this configuration": the check is
				// a query against the database, and a partial document —
				// which is the ordinary case, since --prune defaults off — is
				// meant to reference objects it does not restate. Sending an
				// operator back to their file to look for a node that is
				// missing from the *fleet* is the wrong direction.
				return fmt.Errorf("deployment %q names %s %q, which this control plane does not have",
					d.ID, ref.what, ref.id)
			}
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO deployment
			(id, model_id, node_name, backend, image_digest, params_json, extra_args_json,
			 env_json, port, state, created_at, updated_at)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'defined', ?, ?)
			ON CONFLICT (id) DO UPDATE SET
				model_id = excluded.model_id, node_name = excluded.node_name,
				backend = excluded.backend, image_digest = excluded.image_digest,
				params_json = excluded.params_json,
				extra_args_json = excluded.extra_args_json, env_json = excluded.env_json,
				port = excluded.port,
				updated_at = excluded.updated_at`,
			d.ID, d.ModelID, d.NodeName, d.Backend, nullable(d.Image), orDefault(d.Params, "{}"),
			orDefault(d.ExtraArgs, "[]"), orDefault(d.Env, "{}"),
			nullableInt(int64(d.Port)), stamp(now), stamp(now)); err != nil {
			return fmt.Errorf("applying deployment %q: %w", d.ID, err)
		}
		// The GPU claim is replaced wholesale. Deleting first is what lets a
		// deployment move from GPU 0 to GPU 1 without colliding with itself.
		if _, err := tx.ExecContext(ctx, `DELETE FROM deployment_gpu WHERE deployment_id = ?`, d.ID); err != nil {
			return err
		}
		for _, idx := range d.GPUs {
			if _, err := tx.ExecContext(ctx,
				`INSERT INTO deployment_gpu (deployment_id, node_name, gpu_index) VALUES (?, ?, ?)`,
				d.ID, d.NodeName, idx); err != nil {
				return fmt.Errorf("claiming GPU %d on %s for %q: %w", idx, d.NodeName, d.ID, err)
			}
		}
	}
	return prune(ctx, tx, "deployment", "id", names(have.Deployments, func(d Deployment) string { return d.ID }),
		names(want.Deployments, func(d Deployment) string { return d.ID }), opt, res)
}

// applyGrants replaces the per-user route allowlist wholesale.
//
// Wholesale, and not a merge: this is an allowlist, and the operation an
// administrator most needs to be able to perform on one is *removal*. A merge
// that only ever added would make revoking access something `config apply`
// could not express, which is the one direction that has to work.
// applyGrants adds what the document grants and reports what it does not
// mention, like every other object here.
//
// **It used to begin `DELETE FROM user_route`, unconditionally.** That made any
// partial apply — a new model, a changed port, anything — revoke every user's
// access to every route, and the deletion was invisible: with prune off, Apply
// strips the `- ` lines from the change list, so the verb reported adding a
// model and said nothing about the access it had just destroyed. The symptom is
// 403 on a fleet where nothing else changed, and docs/specs/06-gateway.md §2's
// deny-by-default means nobody can tell that from correct behavior.
//
// Removing a grant is therefore `--prune`, which is how everything else in this
// file is removed.
func applyGrants(ctx context.Context, tx *sql.Tx, now time.Time, want, have *Snapshot, opt Options, res *Result) error {
	for _, g := range want.Grants {
		var userID string
		err := tx.QueryRowContext(ctx, `SELECT id FROM user WHERE name = ?`, g.User).Scan(&userID)
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("grant names user %q, which does not exist", g.User)
		}
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx,
			`INSERT INTO user_route (user_id, route_name, granted_at) VALUES (?, ?, ?)
			 ON CONFLICT (user_id, route_name) DO NOTHING`,
			userID, g.Route, stamp(now)); err != nil {
			return fmt.Errorf("granting %s access to %s: %w", g.User, g.Route, err)
		}
	}
	for _, g := range have.Grants {
		if slices.Contains(want.Grants, g) {
			continue
		}
		key := g.User + "/" + g.Route
		if !opt.Prune {
			res.Orphans = append(res.Orphans, "grant "+key)
			continue
		}
		if _, err := tx.ExecContext(ctx,
			`DELETE FROM user_route WHERE route_name = ?
			   AND user_id = (SELECT id FROM user WHERE name = ?)`, g.Route, g.User); err != nil {
			return err
		}
		res.Changes = append(res.Changes, "- grant "+key)
	}
	return nil
}

func applyRoutes(ctx context.Context, tx *sql.Tx, now time.Time, want, have *Snapshot, opt Options, res *Result) error {
	for _, r := range want.Routes {
		if _, err := tx.ExecContext(ctx,
			`INSERT INTO route (name, strategy, created_at) VALUES (?, ?, ?)
			 ON CONFLICT (name) DO UPDATE SET strategy = excluded.strategy`,
			r.Name, orDefault(r.Strategy, "round-robin"), stamp(now)); err != nil {
			return fmt.Errorf("applying route %q: %w", r.Name, err)
		}
		if _, err := tx.ExecContext(ctx, `DELETE FROM route_member WHERE route_name = ?`, r.Name); err != nil {
			return err
		}
		for _, mem := range r.Members {
			w := mem.Weight
			if w == 0 {
				w = 1
			}
			// Checked before the insert so the refusal names the file's
			// mistake. The foreign key would catch it either way, but
			// "FOREIGN KEY constraint failed (787)" is not something to hand
			// somebody who just edited a TOML file.
			var exists int
			if err := tx.QueryRowContext(ctx,
				`SELECT count(*) FROM deployment WHERE id = ?`, mem.DeploymentID).Scan(&exists); err != nil {
				return err
			}
			if exists == 0 {
				return fmt.Errorf("route %q names deployment %q, which this control plane does not have",
					r.Name, mem.DeploymentID)
			}
			if _, err := tx.ExecContext(ctx,
				`INSERT INTO route_member (route_name, deployment_id, weight) VALUES (?, ?, ?)`,
				r.Name, mem.DeploymentID, w); err != nil {
				return fmt.Errorf("adding %q to route %q: %w", mem.DeploymentID, r.Name, err)
			}
		}
	}
	return prune(ctx, tx, "route", "name", names(have.Routes, func(r Route) string { return r.Name }),
		names(want.Routes, func(r Route) string { return r.Name }), opt, res)
}

func applyLimits(ctx context.Context, tx *sql.Tx, want, have *Snapshot, opt Options, res *Result) error {
	for _, l := range want.Limits {
		if _, err := tx.ExecContext(ctx, `INSERT INTO limits
			(subject_kind, subject_id, rpm, tpm, daily_tokens, max_concurrent)
			VALUES (?, ?, ?, ?, ?, ?)
			ON CONFLICT (subject_kind, subject_id) DO UPDATE SET
				rpm = excluded.rpm, tpm = excluded.tpm,
				daily_tokens = excluded.daily_tokens, max_concurrent = excluded.max_concurrent`,
			l.SubjectKind, l.SubjectID, nullableInt(int64(l.RPM)), nullableInt(int64(l.TPM)),
			nullableInt(int64(l.DailyTokens)), nullableInt(int64(l.MaxConcurrent))); err != nil {
			return fmt.Errorf("applying limits for %s/%s: %w", l.SubjectKind, l.SubjectID, err)
		}
	}
	for _, l := range have.Limits {
		if slices.ContainsFunc(want.Limits, func(x Limit) bool {
			return x.SubjectKind == l.SubjectKind && x.SubjectID == l.SubjectID
		}) {
			continue
		}
		key := l.SubjectKind + "/" + l.SubjectID
		if !opt.Prune {
			res.Orphans = append(res.Orphans, "limits "+key)
			continue
		}
		if _, err := tx.ExecContext(ctx,
			`DELETE FROM limits WHERE subject_kind = ? AND subject_id = ?`, l.SubjectKind, l.SubjectID); err != nil {
			return err
		}
		res.Changes = append(res.Changes, "- limits "+key)
	}
	return nil
}

// prune removes objects absent from the configuration, or reports them.
//
// The table and key names reach a Sprintf. They are compile-time literals from
// the three call sites in this file and never touch anything a caller supplied;
// the values are still bound as parameters. Said out loud because the shape is
// the one that is usually a defect.
func prune(ctx context.Context, tx *sql.Tx, table, key string, have, want []string, opt Options, res *Result) error {
	for _, id := range have {
		if slices.Contains(want, id) {
			continue
		}
		if !opt.Prune {
			res.Orphans = append(res.Orphans, table+" "+id)
			continue
		}
		if _, err := tx.ExecContext(ctx,
			fmt.Sprintf(`DELETE FROM %s WHERE %s = ?`, table, key), id); err != nil {
			return fmt.Errorf("pruning %s %q: %w", table, id, err)
		}
	}
	return nil
}

func names[T any](in []T, key func(T) string) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = key(v)
	}
	return out
}

func stamp(t time.Time) string { return t.UTC().Truncate(time.Millisecond).Format(audit.TimeFormat) }

func orDefault(s, d string) string {
	if s == "" {
		return d
	}
	return s
}

func nullableInt(n int64) any {
	if n == 0 {
		return nil
	}
	return n
}

// checkArtifact refuses a model whose artifact kind its backend cannot read.
//
// The backend is the authority: each descriptor declares one `weights_layout`,
// and a model staged in another one is weights the server will not find. An
// unknown backend is left alone — R6 owns which backends exist, and refusing
// here would make this the second place that decides.
func checkArtifact(m Model) error {
	d, err := backend.Get(m.Backend)
	if err != nil {
		return nil
	}
	if m.Artifact == "" || m.Artifact == d.Backend.WeightsLayout {
		return nil
	}
	return fmt.Errorf("model %q is %q and the %s backend reads %q; "+
		"05 §1 requires the artifact kind to match the backend's weights_layout",
		m.ID, m.Artifact, m.Backend, d.Backend.WeightsLayout)
}
