package minisign

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The whole claim of docs/specs/13-evidence.md §3 is that an assessor checks a
// bundle with the stock tool and no nodary. That is a claim about
// interoperability with a program we do not control, so it is tested against
// that program rather than against our own round trip — which would pass just
// as well if both sides were wrong in the same way.
func minisignBin(t *testing.T) string {
	t.Helper()
	path, err := exec.LookPath("minisign")
	if err != nil {
		t.Skip("minisign is not installed; interoperability is unverified in this run")
	}
	return path
}

// Ours signs, theirs verifies. This is the direction that matters: it is what
// an assessor does with an evidence bundle.
func TestReferenceToolVerifiesOurSignature(t *testing.T) {
	bin := minisignBin(t)
	dir := t.TempDir()

	pub, priv := newKey(t)
	msg := []byte("chain.jsonl\nverify.txt\ncontrols.json\n")

	msgPath := filepath.Join(dir, "manifest.json")
	sigPath := msgPath + ".minisig"
	pubPath := filepath.Join(dir, "nodary-evidence.pub")
	write(t, msgPath, msg)
	write(t, sigPath, []byte(Sign(priv, pub.ID, msg, "nodary evidence bundle")))
	write(t, pubPath, []byte(EncodePublicKey(pub)))

	out, err := exec.Command(bin, "-V", "-m", msgPath, "-x", sigPath, "-p", pubPath).CombinedOutput()
	if err != nil {
		t.Fatalf("minisign refused our signature: %v\n%s", err, out)
	}
	if !strings.Contains(string(out), "Signature and comment signature verified") {
		t.Errorf("minisign did not confirm both signatures:\n%s", out)
	}

	// And it must refuse a member that was edited after signing.
	write(t, msgPath, append(msg, '\n'))
	if out, err := exec.Command(bin, "-V", "-m", msgPath, "-x", sigPath, "-p", pubPath).CombinedOutput(); err == nil {
		t.Errorf("minisign accepted an edited manifest:\n%s", out)
	}
}

// Theirs signs, ours verifies. This is what checking a manifest revision or a
// license looks like, where the signature was made by our release pipeline.
func TestWeVerifyTheReferenceToolsSignature(t *testing.T) {
	bin := minisignBin(t)
	dir := t.TempDir()

	secret := filepath.Join(dir, "key.sec")
	public := filepath.Join(dir, "key.pub")
	// -W is a passwordless key: the release pipeline signs non-interactively.
	if out, err := exec.Command(bin, "-G", "-W", "-s", secret, "-p", public).CombinedOutput(); err != nil {
		t.Fatalf("generating a key: %v\n%s", err, out)
	}

	msgPath := filepath.Join(dir, "components.json")
	write(t, msgPath, []byte(`{"schema":1,"revision":7}`))
	// -l is load-bearing: without it minisign 0.11 writes a prehashed
	// signature, which docs/adr/0007 refuses.
	if out, err := exec.Command(bin, "-S", "-l", "-s", secret, "-m", msgPath,
		"-c", "untrusted", "-t", "nodary manifest revision 7").CombinedOutput(); err != nil {
		t.Fatalf("signing: %v\n%s", err, out)
	}

	pub, err := ParsePublicKey(read(t, public))
	if err != nil {
		t.Fatalf("parsing minisign's own public key: %v", err)
	}
	sig, err := Verify(pub, []byte(read(t, msgPath)), read(t, msgPath+".minisig"))
	if err != nil {
		t.Fatalf("we refused minisign's signature: %v", err)
	}
	if sig.TrustedComment != "nodary manifest revision 7" {
		t.Errorf("trusted comment = %q", sig.TrustedComment)
	}
}

// docs/adr/0007 pins the non-prehashed algorithm, and prehashed is what
// minisign writes when nobody asks for anything. This is the realistic mistake
// — a pipeline that forgets -l — caught against real output rather than a
// forged byte.
func TestTheReferenceToolsDefaultSignatureIsRefused(t *testing.T) {
	bin := minisignBin(t)
	dir := t.TempDir()

	secret := filepath.Join(dir, "key.sec")
	public := filepath.Join(dir, "key.pub")
	if out, err := exec.Command(bin, "-G", "-W", "-s", secret, "-p", public).CombinedOutput(); err != nil {
		t.Fatalf("generating a key: %v\n%s", err, out)
	}
	msgPath := filepath.Join(dir, "big.bin")
	write(t, msgPath, []byte("anything"))
	// No -l: exactly what a pipeline that has not been told produces.
	if out, err := exec.Command(bin, "-S", "-s", secret, "-m", msgPath).CombinedOutput(); err != nil {
		t.Fatalf("signing: %v\n%s", err, out)
	}

	pub, err := ParsePublicKey(read(t, public))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Verify(pub, []byte("anything"), read(t, msgPath+".minisig")); err == nil {
		t.Error("a prehashed signature was accepted")
	} else if !strings.Contains(err.Error(), "-l") {
		t.Errorf("refused, but without naming the flag that fixes it: %v", err)
	}
}

// A key generated by minisign and one generated here must be the same shape,
// or the release pipeline and the verifier disagree about what a key is.
func TestKeyIDsAgreeWithTheReferenceTool(t *testing.T) {
	bin := minisignBin(t)
	dir := t.TempDir()
	public := filepath.Join(dir, "key.pub")
	if out, err := exec.Command(bin, "-G", "-W", "-s", filepath.Join(dir, "key.sec"),
		"-p", public).CombinedOutput(); err != nil {
		t.Fatalf("generating a key: %v\n%s", err, out)
	}

	theirs, err := ParsePublicKey(read(t, public))
	if err != nil {
		t.Fatal(err)
	}
	raw, err := base64.StdEncoding.DecodeString(strings.Split(strings.TrimSpace(read(t, public)), "\n")[1])
	if err != nil {
		t.Fatal(err)
	}
	if len(raw) != 2+keyIDLen+ed25519.PublicKeySize {
		t.Fatalf("minisign's public key is %d bytes, we expect %d", len(raw), 2+keyIDLen+ed25519.PublicKeySize)
	}
	if len(theirs.Key) != ed25519.PublicKeySize {
		t.Errorf("parsed key is %d bytes", len(theirs.Key))
	}
	_ = rand.Reader
}

func write(t *testing.T, path string, b []byte) {
	t.Helper()
	if err := os.WriteFile(path, b, 0o600); err != nil {
		t.Fatal(err)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}
